### ISSUE TITLE
Is this best practice and does it work?

### ISSUE THREAD

**Issue by AmirSavand** [AmirSavand/royale-plus#45]
```python
    mode_1v1 = models.BooleanField(default=True)
    mode_2v2 = models.BooleanField(default=True)
    mode_2x = models.BooleanField(default=True)
    mode_3x = models.BooleanField(default=True)

    @property
    def all_modes(self):
        if self.mode_1v1 and self.mode_2v2 and self.mode_2x and self.mode_3x:
            return True
        return False
```

The `all_modes` property, is it legit?

**Comment by AmirSavand** [comment]
I think I should do that on front-end side.

**Comment by Alir3z4** [comment]
Yeah that's fine to be done in the backend, in matter of fact it should be done here to it would prevent the duplicate code across multiple client code (ex. mobile, web, native or any kind of client code).
However to have a cleaner code, I would suggest you to write:
```python
@property
def all_modes(self) -> bool:
    return all([self.mode_1v1, self.mode_2v2, self.mode_2x, self.mode_3x])
```

To learn more about `all`:

* https://stackoverflow.com/questions/19389490/how-do-pythons-any-and-all-functions-work#19389957
* https://docs.python.org/3.5/library/functions.html#all
